#!/usr/bin/env ansible-playbook
---
# Create a strong ssh-key: ssh-keygen -t id_ed25519 -a 500 -C $USER
# Usage: ./ssh-copy-id.yml -k -i <inventory>

- name: Distribute public ssh-key to ansible inventory
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Set home_dir from $HOME
      ansible.builtin.set_fact:
        home_dir: "{{ lookup('env','HOME') }}"

    - name: Using id_ed25519.pub ssh-key file
      ansible.builtin.set_fact:
        pub_key: "{{ home_dir }}/.ssh/id_ed25519.pub"

    - name: Get remote user
      ansible.builtin.setup:
        filter:
          - 'user_id'

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ ansible_facts.user_id }}"
        state: present
        key: "{{ lookup('file',pub_key)  }}"
        exclusive: true

